# **Series**

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__, np.__version__

('2.3.3', '2.3.4')

In [3]:
serie_dados = pd.Series([10, 20, 30, 40, 50])
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
type(serie_dados)

pandas.core.series.Series

In [5]:
array_inteiros = [10, 20, 30, 40, 50]
indices = ['A', 'B', 'C', 'D', 'E']
serie_dados = pd.Series(array_inteiros, index=indices)
serie_dados

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [6]:
np_array_inteiros = np.array([10, 20, 30, 40, 50])
np_array_inteiros

array([10, 20, 30, 40, 50])

In [7]:
type(np_array_inteiros)

numpy.ndarray

In [8]:
serie_dados = pd.Series(array_inteiros)
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
serie_dados.shape

(5,)

In [10]:
serie_dados.ndim

1

In [11]:
serie_dados.size

5

In [12]:
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
serie_dados.index = ['Z', 'X', 'V', 'A', 'B']
serie_dados

Z    10
X    20
V    30
A    40
B    50
dtype: int64

In [14]:
valores = np.random.random(10)
indexes = np.arange(0, 10)
valores, indexes

(array([0.48348459, 0.68716873, 0.71512942, 0.50975805, 0.75484941,
        0.21914338, 0.39322362, 0.08418005, 0.71285215, 0.33365219]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [15]:
serie_dados = pd.Series(valores, index=indexes)
serie_dados

0    0.483485
1    0.687169
2    0.715129
3    0.509758
4    0.754849
5    0.219143
6    0.393224
7    0.084180
8    0.712852
9    0.333652
dtype: float64

In [16]:
dicionario = {'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}
type(dicionario)

dict

In [17]:
dicionario

{'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}

In [18]:
dict_serie_dados = pd.Series(dicionario)
dict_serie_dados

João       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [19]:
dict_serie_dados.dtype

dtype('int64')

## Fatiamento (slicing)

In [20]:
serie_dados

0    0.483485
1    0.687169
2    0.715129
3    0.509758
4    0.754849
5    0.219143
6    0.393224
7    0.084180
8    0.712852
9    0.333652
dtype: float64

In [21]:
serie_dados[0:3]

0    0.483485
1    0.687169
2    0.715129
dtype: float64

In [22]:
serie_dados[:4]

0    0.483485
1    0.687169
2    0.715129
3    0.509758
dtype: float64

In [23]:
serie_dados[-1:]

9    0.333652
dtype: float64

In [24]:
serie_dados[:-1]

0    0.483485
1    0.687169
2    0.715129
3    0.509758
4    0.754849
5    0.219143
6    0.393224
7    0.084180
8    0.712852
dtype: float64

In [25]:
s2 = serie_dados[:3]
s2

0    0.483485
1    0.687169
2    0.715129
dtype: float64

### Cópia, conversão e concatenação

In [26]:
serie_dados2 = serie_dados.copy()

In [27]:
serie_dados2

0    0.483485
1    0.687169
2    0.715129
3    0.509758
4    0.754849
5    0.219143
6    0.393224
7    0.084180
8    0.712852
9    0.333652
dtype: float64

In [28]:
serie_dados2.dtype

dtype('float64')

In [29]:
serie_dados2.astype(int)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [30]:
serie_dados2.dtype

dtype('float64')

In [31]:
serie_dados2 = serie_dados2.astype(int)

In [32]:
serie_dados2.dtype

dtype('int64')

In [33]:
dados_novos = {'Gustavo': 20, 'Alana': 30}
serie_dados3 = pd.Series(dados_novos)
serie_dados3

Gustavo    20
Alana      30
dtype: int64

In [34]:
dict_serie_dados

João       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [35]:
serie_dados4 = pd.concat([dict_serie_dados, serie_dados3])
serie_dados4

João       10
Alice       5
Gustavo     6
Pedro       9
Gustavo    20
Alana      30
dtype: int64

## Acesso aos dados com iloc
- Acessar elementos pelo índice

In [36]:
dataset = pd.read_csv('../data/census.csv')
dataset

age          workclass  final-weight    education  education-num  \
0       39          State-gov         77516    Bachelors             13   
1       50   Self-emp-not-inc         83311    Bachelors             13   
2       38            Private        215646      HS-grad              9   
3       53            Private        234721         11th              7   
4       28            Private        338409    Bachelors             13   
...    ...                ...           ...          ...            ...   
32556   27            Private        257302   Assoc-acdm             12   
32557   40            Private        154374      HS-grad              9   
32558   58            Private        151910      HS-grad              9   
32559   22            Private        201490      HS-grad              9   
32560   52       Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   
32560   Female         15024             0             40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [37]:
type(dataset)

pandas.core.frame.DataFrame

In [38]:
serie_idade = dataset['age']
serie_idade

0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, Length: 32561, dtype: int64

In [39]:
type(serie_idade)

pandas.core.series.Series

In [40]:
dataset['age'].values, type(dataset['age'].values)

(array([39, 50, 38, ..., 58, 22, 52], shape=(32561,)), numpy.ndarray)

In [41]:
serie_idade.head()

0    39
1    50
2    38
3    53
4    28
Name: age, dtype: int64

In [42]:
serie_idade.head(10)

0    39
1    50
2    38
3    53
4    28
5    37
6    49
7    52
8    31
9    42
Name: age, dtype: int64

In [43]:
serie_idade.tail()

32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, dtype: int64

In [44]:
serie_idade.tail(10)

32551    32
32552    43
32553    32
32554    53
32555    22
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, dtype: int64

In [45]:
serie_idade.iloc[0]

np.int64(39)

In [46]:
serie_idade.iloc[-1]

np.int64(52)

In [47]:
serie_idade.iloc[0:3]

0    39
1    50
2    38
Name: age, dtype: int64

In [48]:
serie_idade.iloc[[0, 2, 4]]

0    39
2    38
4    28
Name: age, dtype: int64

In [49]:
lista_idade = []
for i in serie_idade.items():
    if i[1] > 50:
        lista_idade.append(i[0])

In [50]:
print(lista_idade)

[3, 7, 21, 24, 25, 27, 41, 45, 46, 67, 74, 77, 81, 83, 85, 90, 100, 112, 115, 116, 118, 140, 144, 148, 154, 157, 160, 169, 172, 187, 189, 202, 208, 213, 214, 221, 222, 223, 224, 226, 227, 228, 229, 235, 245, 246, 252, 254, 263, 267, 270, 283, 285, 295, 303, 316, 319, 324, 325, 328, 329, 333, 334, 346, 348, 354, 356, 361, 366, 368, 380, 399, 416, 428, 430, 447, 452, 461, 466, 470, 474, 484, 486, 487, 499, 501, 502, 503, 511, 515, 527, 534, 536, 546, 552, 555, 561, 564, 571, 578, 580, 581, 582, 588, 589, 591, 592, 602, 606, 610, 618, 622, 634, 639, 641, 647, 648, 656, 679, 686, 690, 708, 729, 731, 738, 741, 746, 752, 756, 761, 763, 764, 774, 779, 786, 788, 794, 796, 802, 808, 817, 818, 825, 826, 831, 833, 834, 835, 839, 842, 843, 844, 850, 857, 872, 873, 874, 885, 888, 900, 901, 909, 912, 917, 918, 924, 927, 932, 945, 952, 954, 967, 972, 978, 983, 985, 989, 995, 1005, 1006, 1008, 1010, 1017, 1025, 1034, 1036, 1040, 1046, 1050, 1051, 1053, 1061, 1062, 1082, 1096, 1100, 1113, 1115, 1118, 1

In [51]:
serie_idade.iloc[lista_idade]

3        53
7        52
21       54
24       59
25       56
         ..
32542    72
32548    65
32554    53
32558    58
32560    52
Name: age, Length: 6460, dtype: int64

## Acesso aos dados com loc
- Acessar elementos por "string"