# **Series**

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__, np.__version__

('2.3.3', '2.3.4')

In [3]:
serie_dados = pd.Series([10, 20, 30, 40, 50])
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
type(serie_dados)

pandas.core.series.Series

In [5]:
array_inteiros = [10, 20, 30, 40, 50]
indices = ['A', 'B', 'C', 'D', 'E']
serie_dados = pd.Series(array_inteiros, index=indices)
serie_dados

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [6]:
np_array_inteiros = np.array([10, 20, 30, 40, 50])
np_array_inteiros

array([10, 20, 30, 40, 50])

In [7]:
type(np_array_inteiros)

numpy.ndarray

In [8]:
serie_dados = pd.Series(array_inteiros)
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
serie_dados.shape

(5,)

In [10]:
serie_dados.ndim

1

In [11]:
serie_dados.size

5

In [12]:
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
serie_dados.index = ['Z', 'X', 'V', 'A', 'B']
serie_dados

Z    10
X    20
V    30
A    40
B    50
dtype: int64

In [14]:
valores = np.random.random(10)
indexes = np.arange(0, 10)
valores, indexes

(array([0.51737087, 0.31745451, 0.67399933, 0.64133482, 0.19836928,
        0.45713861, 0.43834196, 0.58755748, 0.87332264, 0.80703783]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [15]:
serie_dados = pd.Series(valores, index=indexes)
serie_dados

0    0.517371
1    0.317455
2    0.673999
3    0.641335
4    0.198369
5    0.457139
6    0.438342
7    0.587557
8    0.873323
9    0.807038
dtype: float64

In [16]:
dicionario = {'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}
type(dicionario)

dict

In [17]:
dicionario

{'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}

In [18]:
dict_serie_dados = pd.Series(dicionario)
dict_serie_dados

João       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [19]:
dict_serie_dados.dtype

dtype('int64')

## Fatiamento (slicing)

In [20]:
serie_dados

0    0.517371
1    0.317455
2    0.673999
3    0.641335
4    0.198369
5    0.457139
6    0.438342
7    0.587557
8    0.873323
9    0.807038
dtype: float64

In [21]:
serie_dados[0:3]

0    0.517371
1    0.317455
2    0.673999
dtype: float64

In [22]:
serie_dados[:4]

0    0.517371
1    0.317455
2    0.673999
3    0.641335
dtype: float64

In [23]:
serie_dados[-1:]

9    0.807038
dtype: float64

In [24]:
serie_dados[:-1]

0    0.517371
1    0.317455
2    0.673999
3    0.641335
4    0.198369
5    0.457139
6    0.438342
7    0.587557
8    0.873323
dtype: float64

In [25]:
s2 = serie_dados[:3]
s2

0    0.517371
1    0.317455
2    0.673999
dtype: float64