# **Series**

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__, np.__version__

('2.3.3', '2.3.4')

In [3]:
serie_dados = pd.Series([10, 20, 30, 40, 50])
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
type(serie_dados)

pandas.core.series.Series

In [5]:
array_inteiros = [10, 20, 30, 40, 50]
indices = ['A', 'B', 'C', 'D', 'E']
serie_dados = pd.Series(array_inteiros, index=indices)
serie_dados

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [6]:
np_array_inteiros = np.array([10, 20, 30, 40, 50])
np_array_inteiros

array([10, 20, 30, 40, 50])

In [7]:
type(np_array_inteiros)

numpy.ndarray

In [8]:
serie_dados = pd.Series(array_inteiros)
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
serie_dados.shape

(5,)

In [10]:
serie_dados.ndim

1

In [11]:
serie_dados.size

5

In [12]:
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
serie_dados.index = ['Z', 'X', 'V', 'A', 'B']
serie_dados

Z    10
X    20
V    30
A    40
B    50
dtype: int64

In [14]:
valores = np.random.random(10)
indexes = np.arange(0, 10)
valores, indexes

(array([0.27800963, 0.04262768, 0.57091582, 0.13402832, 0.08600789,
        0.88228374, 0.89364146, 0.60883877, 0.59026821, 0.97833995]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [15]:
serie_dados = pd.Series(valores, index=indexes)
serie_dados

0    0.278010
1    0.042628
2    0.570916
3    0.134028
4    0.086008
5    0.882284
6    0.893641
7    0.608839
8    0.590268
9    0.978340
dtype: float64

In [16]:
dicionario = {'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}
type(dicionario)

dict

In [17]:
dicionario

{'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}

In [18]:
dict_serie_dados = pd.Series(dicionario)
dict_serie_dados

João       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [19]:
dict_serie_dados.dtype

dtype('int64')

## Fatiamento (slicing)

In [20]:
serie_dados

0    0.278010
1    0.042628
2    0.570916
3    0.134028
4    0.086008
5    0.882284
6    0.893641
7    0.608839
8    0.590268
9    0.978340
dtype: float64

In [21]:
serie_dados[0:3]

0    0.278010
1    0.042628
2    0.570916
dtype: float64

In [22]:
serie_dados[:4]

0    0.278010
1    0.042628
2    0.570916
3    0.134028
dtype: float64

In [23]:
serie_dados[-1:]

9    0.97834
dtype: float64

In [24]:
serie_dados[:-1]

0    0.278010
1    0.042628
2    0.570916
3    0.134028
4    0.086008
5    0.882284
6    0.893641
7    0.608839
8    0.590268
dtype: float64

In [25]:
s2 = serie_dados[:3]
s2

0    0.278010
1    0.042628
2    0.570916
dtype: float64

### Cópia, conversão e concatenação

In [26]:
serie_dados2 = serie_dados.copy()

In [27]:
serie_dados2

0    0.278010
1    0.042628
2    0.570916
3    0.134028
4    0.086008
5    0.882284
6    0.893641
7    0.608839
8    0.590268
9    0.978340
dtype: float64

In [28]:
serie_dados2.dtype

dtype('float64')

In [29]:
serie_dados2.astype(int)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64

In [30]:
serie_dados2.dtype

dtype('float64')

In [31]:
serie_dados2 = serie_dados2.astype(int)

In [32]:
serie_dados2.dtype

dtype('int64')

In [33]:
dados_novos = {'Gustavo': 20, 'Alana': 30}
serie_dados3 = pd.Series(dados_novos)
serie_dados3

Gustavo    20
Alana      30
dtype: int64

In [34]:
dict_serie_dados

João       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [35]:
serie_dados4 = pd.concat([dict_serie_dados, serie_dados3])
serie_dados4

João       10
Alice       5
Gustavo     6
Pedro       9
Gustavo    20
Alana      30
dtype: int64

## Acesso aos dados com iloc
- Acessar elementos pelo índice

In [36]:
dataset = pd.read_csv('../data/census.csv')
dataset

age          workclass  final-weight    education  education-num  \
0       39          State-gov         77516    Bachelors             13   
1       50   Self-emp-not-inc         83311    Bachelors             13   
2       38            Private        215646      HS-grad              9   
3       53            Private        234721         11th              7   
4       28            Private        338409    Bachelors             13   
...    ...                ...           ...          ...            ...   
32556   27            Private        257302   Assoc-acdm             12   
32557   40            Private        154374      HS-grad              9   
32558   58            Private        151910      HS-grad              9   
32559   22            Private        201490      HS-grad              9   
32560   52       Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   
32560   Female         15024             0             40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [37]:
type(dataset)

pandas.core.frame.DataFrame

In [38]:
serie_idade = dataset['age']
serie_idade

0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, Length: 32561, dtype: int64

In [39]:
type(serie_idade)

pandas.core.series.Series

In [40]:
dataset['age'].values, type(dataset['age'].values)

(array([39, 50, 38, ..., 58, 22, 52], shape=(32561,)), numpy.ndarray)

In [41]:
serie_idade.head()

0    39
1    50
2    38
3    53
4    28
Name: age, dtype: int64

In [42]:
serie_idade.head(10)

0    39
1    50
2    38
3    53
4    28
5    37
6    49
7    52
8    31
9    42
Name: age, dtype: int64

In [43]:
serie_idade.tail()

32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, dtype: int64

In [44]:
serie_idade.tail(10)

32551    32
32552    43
32553    32
32554    53
32555    22
32556    27
32557    40
32558    58
32559    22
32560    52
Name: age, dtype: int64

In [45]:
serie_idade.iloc[0]

np.int64(39)

In [46]:
serie_idade.iloc[-1]

np.int64(52)

In [47]:
serie_idade.iloc[0:3]

0    39
1    50
2    38
Name: age, dtype: int64

In [48]:
serie_idade.iloc[[0, 2, 4]]

0    39
2    38
4    28
Name: age, dtype: int64

In [49]:
lista_idade = []
for i in serie_idade.items():
    if i[1] > 50:
        lista_idade.append(i[0])

In [50]:
print(lista_idade)

[3, 7, 21, 24, 25, 27, 41, 45, 46, 67, 74, 77, 81, 83, 85, 90, 100, 112, 115, 116, 118, 140, 144, 148, 154, 157, 160, 169, 172, 187, 189, 202, 208, 213, 214, 221, 222, 223, 224, 226, 227, 228, 229, 235, 245, 246, 252, 254, 263, 267, 270, 283, 285, 295, 303, 316, 319, 324, 325, 328, 329, 333, 334, 346, 348, 354, 356, 361, 366, 368, 380, 399, 416, 428, 430, 447, 452, 461, 466, 470, 474, 484, 486, 487, 499, 501, 502, 503, 511, 515, 527, 534, 536, 546, 552, 555, 561, 564, 571, 578, 580, 581, 582, 588, 589, 591, 592, 602, 606, 610, 618, 622, 634, 639, 641, 647, 648, 656, 679, 686, 690, 708, 729, 731, 738, 741, 746, 752, 756, 761, 763, 764, 774, 779, 786, 788, 794, 796, 802, 808, 817, 818, 825, 826, 831, 833, 834, 835, 839, 842, 843, 844, 850, 857, 872, 873, 874, 885, 888, 900, 901, 909, 912, 917, 918, 924, 927, 932, 945, 952, 954, 967, 972, 978, 983, 985, 989, 995, 1005, 1006, 1008, 1010, 1017, 1025, 1034, 1036, 1040, 1046, 1050, 1051, 1053, 1061, 1062, 1082, 1096, 1100, 1113, 1115, 1118, 1

In [51]:
serie_idade.iloc[lista_idade]

3        53
7        52
21       54
24       59
25       56
         ..
32542    72
32548    65
32554    53
32558    58
32560    52
Name: age, Length: 6460, dtype: int64

## Acesso aos dados com loc
- Acessar elementos por "string"

In [52]:
from faker import Faker

In [53]:
fake = Faker()

In [54]:
indices_name = []
for _ in range(32561):
    indices_name.append(fake.name())

In [55]:
type(indices_name), len(indices_name)

(list, 32561)

In [56]:
serie_idade.size

32561

In [57]:
serie_idade_name = pd.Series(np.array(dataset['age']), index=indices_name)
serie_idade_name

Matthew Dalton      39
Matthew Maynard     50
Michele Williams    38
Brian Watson        53
James Lee           28
                    ..
Charles Gonzalez    27
Janice Espinoza     40
Craig Huffman       58
Makayla Moore       22
Gerald Donovan      52
Length: 32561, dtype: int64

In [58]:
serie_idade_name['Ashley Williams']

Ashley Williams    28
Ashley Williams    53
Ashley Williams    38
Ashley Williams    49
Ashley Williams    60
dtype: int64

In [59]:
serie_idade_name2 = serie_idade_name.drop_duplicates()
serie_idade_name2.size

73

In [60]:
# serie_idade_name2.loc[['Wendy Martin', 'Mercedes Bright MD']]

In [61]:
serie_idade_name3 = serie_idade_name2.copy()
serie_idade_name3

Matthew Dalton         39
Matthew Maynard        50
Michele Williams       38
Brian Watson           53
James Lee              28
                       ..
Dawn Murphy            83
Michael Massey         84
Taylor Cox             85
Devin Cline            86
Jennifer Richardson    87
Length: 73, dtype: int64

In [62]:
serie_idade_name3.reset_index(drop=True)

0     39
1     50
2     38
3     53
4     28
      ..
68    83
69    84
70    85
71    86
72    87
Length: 73, dtype: int64

In [63]:
serie_idade_name3.reset_index(drop=True, inplace=True)

In [64]:
serie_idade_name3.index

RangeIndex(start=0, stop=73, step=1)

## Ordenação

In [65]:
serie_idade_name.sort_values()

Alex Garrison        17
Melinda Butler       17
Brandi Bryant        17
Lindsey Robbins      17
Angela Rhodes        17
                     ..
Joseph Terry         90
Matthew Holt         90
Jacqueline Harris    90
Megan Obrien         90
Robert Anderson      90
Length: 32561, dtype: int64

In [66]:
serie_idade_name.sort_values(ascending=False)

Maria Byrd        90
Brian Morgan      90
James Williams    90
Monica Edwards    90
Lisa Perry        90
                  ..
Robin Farmer      17
Pamela Barnes     17
Pamela Smith      17
Sharon Baker      17
Shawna Paul       17
Length: 32561, dtype: int64

In [67]:
serie_idade_name.sort_index()

Aaron Adams          22
Aaron Andrade        20
Aaron Andrews        69
Aaron Bailey         36
Aaron Baker          38
                     ..
Zachary Zimmerman    35
Zoe Davis            27
Zoe Morrison         32
Zoe Moss             51
Zoe Wu               31
Length: 32561, dtype: int64

In [68]:
serie_idade_name.sort_index(ascending=False)

Zoe Wu               31
Zoe Moss             51
Zoe Morrison         32
Zoe Davis            27
Zachary Zimmerman    35
                     ..
Aaron Baker          38
Aaron Bailey         36
Aaron Andrews        69
Aaron Andrade        20
Aaron Adams          22
Length: 32561, dtype: int64

In [69]:
sr = serie_idade_name.sort_values(ascending=False).iloc[0:11]
sr

Maria Byrd         90
Brian Morgan       90
James Williams     90
Monica Edwards     90
Lisa Perry         90
Gregory Sanchez    90
Brian Smith        90
Mindy Sanchez      90
Carl Contreras     90
Joseph Terry       90
Shannon Bennett    90
dtype: int64

## Contagem

In [70]:
serie_idade_name.value_counts()

36    898
31    888
34    886
23    877
35    876
     ... 
83      6
88      3
85      3
86      1
87      1
Name: count, Length: 73, dtype: int64

In [71]:
serie_idade_name.value_counts(normalize=True)

36    0.027579
31    0.027272
34    0.027210
23    0.026934
35    0.026903
        ...   
83    0.000184
88    0.000092
85    0.000092
86    0.000031
87    0.000031
Name: proportion, Length: 73, dtype: float64

In [72]:
serie_idade_name.value_counts(normalize=True, sort=True)

36    0.027579
31    0.027272
34    0.027210
23    0.026934
35    0.026903
        ...   
83    0.000184
88    0.000092
85    0.000092
86    0.000031
87    0.000031
Name: proportion, Length: 73, dtype: float64

In [73]:
serie_idade_name.value_counts(bins=10)

(38.9, 46.2]      6163
(31.6, 38.9]      6048
(24.3, 31.6]      5890
(16.926, 24.3]    5570
(46.2, 53.5]      3967
(53.5, 60.8]      2591
(60.8, 68.1]      1595
(68.1, 75.4]       496
(75.4, 82.7]       174
(82.7, 90.0]        67
Name: count, dtype: int64

## Filtros

In [74]:
fake.country()

'Mayotte'

In [75]:
indices_pais = []
for _ in range(32561):
    indices_pais.append(fake.country())

In [76]:
indices_pais[0:11]

['Uganda',
 'Qatar',
 'Holy See (Vatican City State)',
 'Angola',
 'Turkmenistan',
 'Gabon',
 'Niger',
 'Kuwait',
 'Cook Islands',
 'Bhutan',
 'Niue']

In [77]:
serie_pais = pd.Series(np.array(dataset['age']), index=indices_pais)
serie_pais

Uganda                           39
Qatar                            50
Holy See (Vatican City State)    38
Angola                           53
Turkmenistan                     28
                                 ..
Malawi                           27
Guam                             40
Hungary                          58
Brazil                           22
Brazil                           52
Length: 32561, dtype: int64

In [78]:
serie_pais.loc[serie_pais>50]

Angola                  53
Kuwait                  52
Japan                   54
Lebanon                 59
United Arab Emirates    56
                        ..
Morocco                 72
Sierra Leone            65
Serbia                  53
Hungary                 58
Brazil                  52
Length: 6460, dtype: int64

In [79]:
serie_pais.loc[(serie_pais > 50) & (serie_pais.index == "India")]

India    55
India    54
India    57
India    58
India    64
India    55
India    69
India    76
India    60
India    62
India    62
India    57
India    71
India    76
India    66
India    58
India    60
India    55
India    66
India    60
India    52
India    67
India    59
India    57
India    60
India    53
India    73
dtype: int64

In [80]:
serie_pais.index.isin(["India", "Brazil"])

array([False, False, False, ..., False,  True,  True], shape=(32561,))

In [81]:
~serie_pais.index.isin(["India", "Brazil"])

array([ True,  True,  True, ...,  True, False, False], shape=(32561,))

## Operações matemáticas

In [82]:
serie_pais + 2

Uganda                           41
Qatar                            52
Holy See (Vatican City State)    40
Angola                           55
Turkmenistan                     30
                                 ..
Malawi                           29
Guam                             42
Hungary                          60
Brazil                           24
Brazil                           54
Length: 32561, dtype: int64

In [83]:
serie_pais.add(2)

Uganda                           41
Qatar                            52
Holy See (Vatican City State)    40
Angola                           55
Turkmenistan                     30
                                 ..
Malawi                           29
Guam                             42
Hungary                          60
Brazil                           24
Brazil                           54
Length: 32561, dtype: int64

In [84]:
serie_pais.sub(2)

Uganda                           37
Qatar                            48
Holy See (Vatican City State)    36
Angola                           51
Turkmenistan                     26
                                 ..
Malawi                           25
Guam                             38
Hungary                          56
Brazil                           20
Brazil                           50
Length: 32561, dtype: int64

In [85]:
serie_pais.mul(2)

Uganda                            78
Qatar                            100
Holy See (Vatican City State)     76
Angola                           106
Turkmenistan                      56
                                ... 
Malawi                            54
Guam                              80
Hungary                          116
Brazil                            44
Brazil                           104
Length: 32561, dtype: int64

In [86]:
serie_pais.div(2)

Uganda                           19.5
Qatar                            25.0
Holy See (Vatican City State)    19.0
Angola                           26.5
Turkmenistan                     14.0
                                 ... 
Malawi                           13.5
Guam                             20.0
Hungary                          29.0
Brazil                           11.0
Brazil                           26.0
Length: 32561, dtype: float64

In [87]:
s1 = pd.Series([20, 30, 40])
s2 = pd.Series([1, 2, 3])
s1, s2

(0    20
 1    30
 2    40
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [88]:
s1.add(s2)

0    21
1    32
2    43
dtype: int64

In [89]:
s1.sub(s2), s1.mul(s2), s1.div(s2)

(0    19
 1    28
 2    37
 dtype: int64,
 0     20
 1     60
 2    120
 dtype: int64,
 0    20.000000
 1    15.000000
 2    13.333333
 dtype: float64)

## Operações com strings

In [90]:
serie_pais

Uganda                           39
Qatar                            50
Holy See (Vatican City State)    38
Angola                           53
Turkmenistan                     28
                                 ..
Malawi                           27
Guam                             40
Hungary                          58
Brazil                           22
Brazil                           52
Length: 32561, dtype: int64

In [91]:
serie_pais_index = serie_pais.index.to_series()
serie_pais_index

Uganda                                                  Uganda
Qatar                                                    Qatar
Holy See (Vatican City State)    Holy See (Vatican City State)
Angola                                                  Angola
Turkmenistan                                      Turkmenistan
                                             ...              
Malawi                                                  Malawi
Guam                                                      Guam
Hungary                                                Hungary
Brazil                                                  Brazil
Brazil                                                  Brazil
Length: 32561, dtype: object

In [92]:
serie_pais_index.reset_index(drop=True, inplace=True)
serie_pais_index

0                               Uganda
1                                Qatar
2        Holy See (Vatican City State)
3                               Angola
4                         Turkmenistan
                     ...              
32556                           Malawi
32557                             Guam
32558                          Hungary
32559                           Brazil
32560                           Brazil
Length: 32561, dtype: object

In [93]:
serie_pais_index.str.contains('tse')

0        False
1        False
2        False
3        False
4        False
         ...  
32556    False
32557    False
32558    False
32559    False
32560    False
Length: 32561, dtype: bool

In [94]:
serie_pais_index.str.upper()

0                               UGANDA
1                                QATAR
2        HOLY SEE (VATICAN CITY STATE)
3                               ANGOLA
4                         TURKMENISTAN
                     ...              
32556                           MALAWI
32557                             GUAM
32558                          HUNGARY
32559                           BRAZIL
32560                           BRAZIL
Length: 32561, dtype: object

In [95]:
serie_pais_index.str.lower()

0                               uganda
1                                qatar
2        holy see (vatican city state)
3                               angola
4                         turkmenistan
                     ...              
32556                           malawi
32557                             guam
32558                          hungary
32559                           brazil
32560                           brazil
Length: 32561, dtype: object

In [96]:
serie_pais_index.str.strip("Faso")

0                                Ugand
1                                Qatar
2        Holy See (Vatican City State)
3                                Angol
4                         Turkmenistan
                     ...              
32556                           Malawi
32557                             Guam
32558                          Hungary
32559                           Brazil
32560                           Brazil
Length: 32561, dtype: object

In [97]:
serie_pais_index.str.split(" ", expand=True)

0     1         2     3       4     5     6     7
0            Uganda  None      None  None    None  None  None  None
1             Qatar  None      None  None    None  None  None  None
2              Holy   See  (Vatican  City  State)  None  None  None
3            Angola  None      None  None    None  None  None  None
4      Turkmenistan  None      None  None    None  None  None  None
...             ...   ...       ...   ...     ...   ...   ...   ...
32556        Malawi  None      None  None    None  None  None  None
32557          Guam  None      None  None    None  None  None  None
32558       Hungary  None      None  None    None  None  None  None
32559        Brazil  None      None  None    None  None  None  None
32560        Brazil  None      None  None    None  None  None  None

[32561 rows x 8 columns]

In [98]:
serie_pais_index.str[0:5]

0        Ugand
1        Qatar
2        Holy 
3        Angol
4        Turkm
         ...  
32556    Malaw
32557     Guam
32558    Hunga
32559    Brazi
32560    Brazi
Length: 32561, dtype: object

## Agrupamento numérico

In [99]:
serie_pais

Uganda                           39
Qatar                            50
Holy See (Vatican City State)    38
Angola                           53
Turkmenistan                     28
                                 ..
Malawi                           27
Guam                             40
Hungary                          58
Brazil                           22
Brazil                           52
Length: 32561, dtype: int64

In [100]:
serie_pais.sum()

np.int64(1256257)

In [101]:
serie_pais.mean()

np.float64(38.58164675532078)

In [102]:
serie_pais.median()

np.float64(37.0)

In [103]:
serie_pais.std()

np.float64(13.640432553581341)

In [104]:
serie_pais.count()

np.int64(32561)

In [105]:
serie_pais.var()

np.float64(186.0614002488016)

In [106]:
serie_pais.loc["Brazil"].mean()

np.float64(35.62992125984252)

In [107]:
serie_pais.loc["India"].mean()

np.float64(39.982608695652175)

In [108]:
serie_pais.quantile([0.25, 0.5, 0.75])

0.25    28.0
0.50    37.0
0.75    48.0
dtype: float64

## Agrupamento categórico

In [109]:
serie_pais_index

0                               Uganda
1                                Qatar
2        Holy See (Vatican City State)
3                               Angola
4                         Turkmenistan
                     ...              
32556                           Malawi
32557                             Guam
32558                          Hungary
32559                           Brazil
32560                           Brazil
Length: 32561, dtype: object

In [110]:
serie_pais_index.value_counts()

Congo                   267
Korea                   258
Pitcairn Islands        166
Kiribati                163
Cayman Islands          160
                       ... 
Mauritius               111
Sweden                  108
Netherlands Antilles    107
Eritrea                 107
Bermuda                 105
Name: count, Length: 243, dtype: int64

In [111]:
serie_pais_index.value_counts(normalize=True)

Congo                   0.008200
Korea                   0.007924
Pitcairn Islands        0.005098
Kiribati                0.005006
Cayman Islands          0.004914
                          ...   
Mauritius               0.003409
Sweden                  0.003317
Netherlands Antilles    0.003286
Eritrea                 0.003286
Bermuda                 0.003225
Name: proportion, Length: 243, dtype: float64

In [112]:
serie_pais_index.unique()

array(['Uganda', 'Qatar', 'Holy See (Vatican City State)', 'Angola',
       'Turkmenistan', 'Gabon', 'Niger', 'Kuwait', 'Cook Islands',
       'Bhutan', 'Niue', 'French Southern Territories', 'Burundi',
       'Tokelau', 'Trinidad and Tobago', 'Jamaica', 'Luxembourg',
       'United States of America', "Cote d'Ivoire", 'Reunion',
       'Netherlands', 'Japan', 'Serbia', 'Uzbekistan', 'Lebanon',
       'United Arab Emirates', 'Greenland', 'Finland', 'Kenya',
       'United States Minor Outlying Islands', 'Hong Kong',
       'Netherlands Antilles', 'Kazakhstan', 'Montenegro', 'Chile',
       'Zimbabwe', 'Costa Rica', 'Mauritania', 'Bolivia', 'Egypt',
       'Malawi', 'Namibia', 'New Caledonia',
       'South Georgia and the South Sandwich Islands', 'Sweden',
       'Estonia', 'Comoros', 'Palestinian Territory', 'Nepal',
       'Madagascar', 'Malta', 'Mayotte', 'Cape Verde', 'Mali', 'Fiji',
       'North Macedonia', 'Switzerland', 'Togo', 'Nicaragua', 'Tuvalu',
       'Guinea-Bissau', 'Ce

In [113]:
serie_pais_index.nunique()

243

## Valores faltantes

In [114]:
serie_faltante = pd.Series([1, 2, 3, np.nan, 5, np.nan])
serie_faltante

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
5    NaN
dtype: float64

In [115]:
serie_faltante.isna()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [116]:
serie_faltante.isna().sum()

np.int64(2)

In [117]:
serie_faltante.value_counts(dropna=False)

NaN    2
1.0    1
2.0    1
3.0    1
5.0    1
Name: count, dtype: int64

In [118]:
serie_faltante.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    5.0
5    0.0
dtype: float64

In [119]:
serie_faltante.dropna()

0    1.0
1    2.0
2    3.0
4    5.0
dtype: float64

In [120]:
serie_faltante.fillna(serie_faltante.mean())

0    1.00
1    2.00
2    3.00
3    2.75
4    5.00
5    2.75
dtype: float64

In [121]:
serie_faltante = pd.Series(["Maçã", "Banana", "Arroz", "Arroz", np.nan, "Batata"])
serie_faltante

0      Maçã
1    Banana
2     Arroz
3     Arroz
4       NaN
5    Batata
dtype: object

In [122]:
serie_faltante.isna().sum()

np.int64(1)

In [123]:
serie_faltante.fillna("Não informado")

0             Maçã
1           Banana
2            Arroz
3            Arroz
4    Não informado
5           Batata
dtype: object

In [124]:
serie_faltante.mode()

0    Arroz
dtype: object

In [125]:
serie_faltante.fillna(serie_faltante.mode().loc[0])

0      Maçã
1    Banana
2     Arroz
3     Arroz
4     Arroz
5    Batata
dtype: object

## Funções