# **Series**

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__, np.__version__

('2.3.3', '2.3.4')

In [3]:
serie_dados = pd.Series([10, 20, 30, 40, 50])
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
type(serie_dados)

pandas.core.series.Series

In [5]:
array_inteiros = [10, 20, 30, 40, 50]
indices = ['A', 'B', 'C', 'D', 'E']
serie_dados = pd.Series(array_inteiros, index=indices)
serie_dados

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [6]:
np_array_inteiros = np.array([10, 20, 30, 40, 50])
np_array_inteiros

array([10, 20, 30, 40, 50])

In [7]:
type(np_array_inteiros)

numpy.ndarray

In [8]:
serie_dados = pd.Series(array_inteiros)
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
serie_dados.shape

(5,)

In [10]:
serie_dados.ndim

1

In [11]:
serie_dados.size

5

In [12]:
serie_dados

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
serie_dados.index = ['Z', 'X', 'V', 'A', 'B']
serie_dados

Z    10
X    20
V    30
A    40
B    50
dtype: int64

In [14]:
valores = np.random.random(10)
indexes = np.arange(0, 10)
valores, indexes

(array([0.19084048, 0.31184139, 0.96291758, 0.05971446, 0.08579104,
        0.91279489, 0.50663863, 0.12626925, 0.12067123, 0.45941723]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [15]:
serie_dados = pd.Series(valores, index=indexes)
serie_dados

0    0.190840
1    0.311841
2    0.962918
3    0.059714
4    0.085791
5    0.912795
6    0.506639
7    0.126269
8    0.120671
9    0.459417
dtype: float64

In [16]:
dicionario = {'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}
type(dicionario)

dict

In [17]:
dicionario

{'João': 10, 'Alice': 5, 'Gustavo': 6, 'Pedro': 9}

In [18]:
dict_serie_dados = pd.Series(dicionario)
dict_serie_dados

João       10
Alice       5
Gustavo     6
Pedro       9
dtype: int64

In [19]:
dict_serie_dados.dtype

dtype('int64')